version: '3'
services:
  nginx:
    container_name: 'nginx'
    build:
      context: './'
      dockerfile: './nginx/Dockerfile'
    depends_on:
      - 'grapher-api'
    ports:
      - '80:80'
      - '443:443'
  mongo:
    container_name: 'mongo'
    image: 'mongo'
    expose:
      - '27017'
  grapher-api:
    container_name: 'grapher-api'
    build:
      context: './grapher-api/'
      dockerfile: 'Dockerfile'
    depends_on:
      - 'mongo'
    expose:
      - '80'
